---
name: Common Settings
match:
  - D:/Projects/C#/test.xml
actions:
  - path: //appSettings/add[@key='MyApplication.MongoDB']/@value
    value: http://localhost:27017
  - path: //appSettings/add[@key='MyApplication.SqlDatabase']
    action: remove
  - appSetting: MyApplication.AdminUsername
    value: RichTea
  - appSetting: owin:AppStartup
    value: Cdsm.IAM.WebUtility.Startup.Cookies
...
